### ISSUE TITLE
Support for ECDSA public keys

### ISSUE THREAD

**Issue by fantamiracle** [cbaker6/iOSCSRSwift#5]
I am wondering if you have any plans to support ECDSA public keys as well. I tried your code and it works for RSA very well, but for ecdsa, it seems we need to have another `buildPublicKeyInfo` as public keys for ecdsa look different.

**Comment by vladasdrejeris** [comment]
Hi, 
We are also trying to use this code in our application to generate CSR and we need to use ECDSA keys, it would be very nice if you added support for ECDSA keys too.

**Comment by cbaker6** [comment]
@fantamiracle and @vladasdrejeris  support for EC has been added. Please note that iOS only supports 256 bit keys.
