### ISSUE TITLE
GPL 2.0 licensed?

### ISSUE THREAD

**Issue by hyandell** [cbaker6/iOSCSRSwift#6]
Hi Corey,

Did you port ios-csr via some form of clean room methodology so that the GPL 2.0 doesn't apply to your code? Usually it seems that ports contain the licensing of the thing that was ported.

**Comment by cbaker6** [comment]
@hyandell thank you for pointing this out, I have changed the license to GPL

**Comment by benaubin** [comment]
@cbaker6 Technically, it may be illegal to use this library in an app on the App Store (and your source code is forced to be made public) - while you can't change the license unless your dependencies do, I've left a comment on an [open issue](https://github.com/ateska/ios-csr/issues/1). If the license is changed, it would be great if you can change yours as well.
