### ISSUE TITLE
Signature FAILED - CSR has an invalid signature problem using this library

### ISSUE THREAD

**Issue by iosdevninja** [cbaker6/iOSCSRSwift#7]
Hello Corey,

We're using your iOSCSRSwift library in order to generate a valid CSR file on a Swift 3 Project but once it is generated and we tested against https://redkestrel.co.uk/products/decoder/ it has this 
Signature | FAILED - CSR has an invalid signature problem.

The rest of the CSR seems fine.

I am including the code we're using based on your library and also the generated CSR  

[CSR.zip](https://github.com/cbaker6/iOSCSRSwift/files/1218662/CSR.zip)

When tested from CLI and it gives usan error.

openssl req -text -verify -in netki.csr
verify failure
38978:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block
type is not
01:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/rsa/rsa_pk1.c:102:
38978:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check
failed:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/rsa/rsa_eay.c:719:
38978:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP
lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/asn1/a_verify.c:191:

Kind regards

**Comment by cbaker6** [comment]
Hi @iosdevninja,

I checked one of my generated certificates and I don't run into this issue. I have attached a screenshot for reference.

My thinking is this is not an issue with this framework but an issue with your code. My reasoning for this is I quickly looked through your code (I don't have much time this week) and see a problem which could be causing your issue. Line 101 of your code you have:

`let csrString = csrBuild.base64EncodedString(options: Data.Base64EncodingOptions(rawValue: 0))`

This will not work. In iOSCSRSwiftTests.swift, I state this should be:

`let csrString = csrBuild.base64EncodedString(options: Data.Base64EncodingOptions(rawValue: 0)).addingPercentEncoding(withAllowedCharacters: CharacterSet.alphanumerics)`

The line below should work as well (depending on your swift version):

`let csrString = csrBuild.base64EncodedString(options: Data.Base64EncodingOptions(rawValue: 0)).stringByAddingPercentEncodingForFormUrlencoded()!`

Encoding incorrectly will definitely cause your CSR to fail.

[CSR Decoder and Certificate Decoder.pdf](https://github.com/cbaker6/iOSCSRSwift/files/1225740/CSR.Decoder.and.Certificate.Decoder.pdf)

If there is still an issue, I won't be able to look at it until next week. 

Let me know if this solves your problem.

**Comment by iosdevninja** [comment]
Hello Corey,

Thank you very much for your prompt reply.

I did the code change as you suggested (Swift 3 one)

let csrString = csrBuild.base64EncodedString(options: Data.Base64EncodingOptions(rawValue: 0)).addingPercentEncoding(withAllowedCharacters: CharacterSet.alphanumerics)

and then print out the new generated CSR string.

I am enclosing it as an attachment on this thread.

The problem is it is still NOT working when tested in https://redkestrel.co.uk/products/decoder/

If you check on the new generated CSR now it comes with % values all across the text.

Please provide advice when you have a free moment.

Kind regards

[CSR_After_Code_Change.zip](https://github.com/cbaker6/iOSCSRSwift/files/1225918/CSR_After_Code_Change.zip)

**Comment by cbaker6** [comment]
@iosdevninja it appears the encoding line I gave you earlier was still correct. Correcting two lines of your code will fix your problem:

`let csrString = csrBuild.base64EncodedString(options: Data.Base64EncodingOptions(rawValue: 0)).addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)`
        
`let formattedCSRString = String(format:"%@%@%@","-----BEGIN CERTIFICATE REQUEST-----\n", csrString!, "\n-----END CERTIFICATE REQUEST-----\n")`

I have attached the CSR created using your code. My apologies for the late reply.

[CSR Decoder and Certificate Decoder.pdf](https://github.com/cbaker6/iOSCSRSwift/files/1339645/CSR.Decoder.and.Certificate.Decoder.pdf)

**Comment by cbaker6** [comment]
@iosdevninja I added two methods which encodes the CSR for you:

Full CSR string:
`let builtCSR = csr.buildCSRAndReturnString(publicKeyBits, privateKey: privateKey)`

CSR without header and footer:
`let builtCSR = csr.buildAndEncodeDataAsString(publicKeyBits, privateKey: privateKey)`
